// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Dummy values for build-time if env vars are missing
const DUMMY_URL = 'https://placeholder.supabase.co';
const DUMMY_KEY = 'placeholder-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || DUMMY_URL,
  SUPABASE_PUBLISHABLE_KEY || DUMMY_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Export flag to check if credentials are properly configured at runtime
export const hasSupabaseCredentials = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);